version: '3'

services:
  app:
    build: .
    image: frontpage
    container_name: frontpage
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
      - ./app:/app
    restart: unless-stopped
    ports: 
      - 8000:8000
    user: 1000:1000
