version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    image: frontpage:v1
    container_name: frontpage
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
      - ./app:/app
      - /mnt/data:/data
    restart: unless-stopped
    ports: 
      - 8000:8000
    user: 1000:1000
