version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontpage:v1
    container_name: frontpage_app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data:/data
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SQLITE_DB_PATH=/data/frontpage.sqlite3
      - PORT=8000
