version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontpage:v1
    container_name: frontpage_app
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
