# Generated by Django 3.1.7 on 2021-04-04 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20210404_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
