# Generated by Django 3.2 on 2021-04-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='uuid',
            new_name='id',
        ),
    ]
