# Generated by Django 3.2 on 2021-04-24 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_rename_uuid_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
    ]
