# Generated by Django 3.1.7 on 2021-04-04 06:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20210404_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 6, 12, 47, 303883, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
