# Generated by Django 3.1.7 on 2021-04-04 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20210404_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 6, 14, 55, 390476, tzinfo=utc), verbose_name='date created'),
        ),
    ]
