# Generated by Django 3.1.7 on 2021-04-05 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20210404_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='home_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
