# Generated by Django 3.2 on 2021-06-25 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_alter_feed_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
