# Generated by Django 3.2 on 2021-11-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20210626_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='filter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
