# Generated by Django 3.2 on 2022-01-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_feed_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
